Step 1.9: After initializing method added to the Playground class still got another error expecting that
bundle exec rspec
1) Playground when there are no children is quite boring place
     Failure/Error: mood = playground.mood

     NoMethodError:
       undefined method `mood' for #<Playground:0x00000001c493d8>
     # ./spec/playground_spec.rb:13:in `block (3 levels) in <top (required)>'