Step 1.4: Added initialize method to over come the error but after adding the initialize(digits_string) then test case is not satisfied because our test case should add the sum of the given digits we don't have that method run : "ruby string_calculator.rb"
NoMethodError: undefined method `sum' for #<Calculator:0x00000001983f18>
    string_calculator.rb:11:in `block (2 levels) in <main>'