Step 1.4: Written a spec to expect gutter game score to be zero
bundle exec rspec

Failure

1) BowlingGame scores a gutter game
     Failure/Error: game.pins([0] * 20)

     NoMethodError:
       undefined method `pins' for #<BowlingGame:0x000000020a76c8>