Step 1.26: Use simple form instead of default rails form so we need to add that gem.
Run: rspec

    1) create new achievement create new achievement with valid data
     Failure/Error: <%= simple_form_for @achievement do |f| %>

     ActionView::Template::Error:
       undefined method `simple_form_for' for #<#<Class:0x00000006d16db0>:0x00000006d151b8>
       Did you mean?  simple_format